services:
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_ENVIRONMENT: Development
      Jwt__Key: "${JWT_KEY:-dev_32bytes_minimum_base64_or_random_string_XXXXXXXX}"
      Jwt__Issuer: "collabtask"
      Jwt__Audience: "collabtask"
    # In dev we expose the API directly to the host on 8080
    ports: ["8080:8080"]
    profiles: ["dev"]

  sql:
    # For dev we expose SQL Server to host on 1433 (connect with SSMS, DBeaver, etc.)
    ports: ["1433:1433"]
    profiles: ["dev"]