name: CI
on: [push, pull_request]

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore api/CollabTask.sln --nologo

      - name: Build (Release)
        run: dotnet build api/CollabTask.sln --configuration Release --no-restore --nologo

      - name: Test (with coverage + threshold)
        run: |
          dotnet test api/CollabTask.sln \
            --configuration Release --no-build --nologo \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=cobertura
        env:
          ASPNETCORE_ENVIRONMENT: Testing
          DISABLE_DB_INIT: "true"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            **/TestResults/*.trx
            **/TestResults/*/coverage.cobertura.xml
          if-no-files-found: warn

  contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - run: npm ci || npm i
      - run: npm run check:contract